export default class Compendium {
	static ACTION_SHOVE = "Compendium.pf2e.actionspf2e.7blmbDrQFNfdT731"
	static ACTION_TRIP = "Compendium.pf2e.actionspf2e.ge56Lu1xXVFYUnLP"
	static ACTION_ESCAPE = "Compendium.pf2e.actionspf2e.SkZAQRkLLkmBQNB9"
	static ACTION_STEP = "Compendium.pf2e.actionspf2e.UHpkTuCtyaPqiCAB"
	static ACTION_STRIDE = "Compendium.pf2e.actionspf2e.Bcxarzksqt9ezrs6"
	static ACTION_INTERACT = "Compendium.pf2e.actionspf2e.pvQ5rY2zrtPI614F"
	static ACTION_MOUNT = "Compendium.pf2e.actionspf2e.PM5jvValFkbFH3TV"
	static ACTION_READY = "Compendium.pf2e.actionspf2e.dLgAMt3TbkmLkUqE"
	static ACTION_RELEASE = "Compendium.pf2e.actionspf2e.wQYmDStjdjn0I26t"
	static ACTION_SUSTAIN_A_SPELL = "Compendium.pf2e.actionspf2e.3f5DMFu8fPiqHpRg"
	static ACTION_SUSTAIN_AN_ACTIVATION = "Compendium.pf2e.actionspf2e.XSGlLjI80LDCimAP"
	static ACTION_CRAWL = "Compendium.pf2e.actionspf2e.Tj055UcNm6UEgtCg"
	static ACTION_LEAP = "Compendium.pf2e.actionspf2e.d5I6018Mci2SWokk"
	static ACTION_POINT_OUT = "Compendium.pf2e.actionspf2e.sn2hIy1iIJX9Vpgj"
	static ACTION_AVERT_GAZE = "Compendium.pf2e.actionspf2e.UWdRX1VelipCzrCg"
	static ACTION_SWIM = "Compendium.pf2e.actionspf2e.c8TGiZ48ygoSPofx"
	static ACTION_CLIMB = "Compendium.pf2e.actionspf2e.pprgrYQ1QnIDGZiy"
	static ACTION_ADMINISTER_FIRST_AID = "Compendium.pf2e.actionspf2e.MHLuKy4nQO2Z4Am1"
	static ACTION_CREATE_A_DIVERSION = "Compendium.pf2e.actionspf2e.GkmbTGfg8KcgynOA"
	static ACTION_SNEAK = "Compendium.pf2e.actionspf2e.VMozDqMMuK5kpoX4"
	
	static ACTION_AVOID_NOTICE = "Compendium.pf2e.actionspf2e.IE2nThCmoyhQA0Jn"
	static ACTION_DEFEND = "Compendium.pf2e.actionspf2e.cYtYKa1gDEl7y2N0"
	static ACTION_DETECT_MAGIC = "Compendium.pf2e.actionspf2e.Yb0C1uLzeHrVLl7a"
	static ACTION_FOLLOW_THE_EXPERT = "Compendium.pf2e.actionspf2e.tfa4Sh7wcxCEqL29"
	static ACTION_HUSTLE = "Compendium.pf2e.actionspf2e.JuqmIAnkL9hVGai8"
	static ACTION_INVESTIGATE = "Compendium.pf2e.actionspf2e.EwgTZBWsc8qKaViP"
	static ACTION_REFOCUS = "Compendium.pf2e.actionspf2e.OSefkMgojBLqmRDh"
	static ACTION_REPEAT_A_SPELL = "Compendium.pf2e.actionspf2e.OQaFzDtVEOMWizJJ"
	static ACTION_SCOUT = "Compendium.pf2e.actionspf2e.kV3XM0YJeS2KCSOb"
	static ACTION_SEARCH = "Compendium.pf2e.actionspf2e.TiNDYUGlMmxzxBYU"
	
	static ACTION_RETRAINING = "Compendium.pf2e.actionspf2e.24PSsn1SKpUwYA1X"
	static EFFECT_MULTIPLE_ATTACK = "Compendium.pf2e-tools-mks.core-effects.DPVfUT43aCQMvauJ"
	static EFFECT_AID_READY = "Compendium.pf2e-tools-mks.core-effects.p9PSILLD0f0NkBc5"
	static EFFECT_AIDED = "Compendium.pf2e-tools-mks.core-effects.lgOBZWFDOE9xIXzS"
	static EFFECT_GRABBING = "Compendium.pf2e-tools-mks.core-effects.gAMtcNpDb57hxSrC"
	static EFFECT_COVER = "Compendium.pf2e-tools-mks.core-effects.SSVgCBCgk98E2VpI"
	static EFFECT_COVER_TAKEN = "Compendium.pf2e-tools-mks.core-effects.U7wkXUO0YGVkKNRA"
	static EFFECT_RAISE_A_SHIELD = "Compendium.pf2e.equipment-effects.2YgXoHvJfrDHucMr"
	static EFFECT_DISARM_SUCCESS = "Compendium.pf2e.equipment-effects.z3ATL8DcRVrT0Uzt"
	static EFFECT_RESIST_A_DIVERSION = "Compendium.pf2e-tools-mks.core-effects.GK9OckuuNDJFdFDe"
	static EFFECT_IMMUNE_TO_DEMORALIZE = "Compendium.pf2e-tools-mks.core-effects.0mPMeOFZfos07cut"
	static EFFECT_POISON_TREATED = "Compendium.pf2e-tools-mks.core-effects.9CucVXo0BT77gw2h"
	
	static EFFECT_DISEASE_TREATED = "Compendium.pf2e-tools-mks.core-effects.VhUYetlOZu2PQGQZ"
	static CONDITION_GRABBED = "Compendium.pf2e.conditionitems.kWc1fhmv9LBiTuei"
	
	static CONDITION_RESTRAINED = "Compendium.pf2e.conditionitems.VcDeM8A5oI6VqhbM"
	static CONDITION_UNNOTICED = "Compendium.pf2e.conditionitems.9evPzg9E6muFcoSk"
	static CONDITION_UNDETECTED = "Compendium.pf2e.conditionitems.VRSef5y1LmL2Hkjf"
	static CONDITION_HIDDEN = "Compendium.pf2e.conditionitems.iU0fEDdBp3rXpTMC"
	static CONDITION_OBSERVED = "Compendium.pf2e.conditionitems.1wQY3JYyhMYeeV2G"
}